name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  frontend-tests:
    name: Frontend (Jest)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        env:
          CI: true
        run: npm test -- --ci

  frontend-build:
    name: Frontend (Vite build)
    runs-on: ubuntu-latest
    needs: frontend-tests

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build with Vite
        run: npm run build

      - name: Upload built assets (Laravel Vite -> public/build)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vite-build
          path: |
            public/build
            dist
          if-no-files-found: ignore
